openapi: "3.0.3"

info:
  version: 1.0.0
  title: Hello World
  description: |
    # Overview
    This is an example API that allows software developers to test that their applications can connect with the HMRC API Platform. It also acts as a hands-on tutorial for developers to get started with HMRC APIs.

    It includes resources for testing access to the three different access levels:

    - Say hello world is an example of an unrestricted endpoint
    - Say hello user is an example of a user-restricted endpoint
    - Say hello application is an example of an application-restricted endpoint
    
    Further details of the different access levels are given on 
    the [Authorisation](/api-documentation/docs/authorisation) page.

    For more information about how to develop your own client applications, including example clients
    for this API, see [Tutorials](/api-documentation/docs/tutorials).

    # Versioning
    When an API changes in a way that is backwards-incompatible, we increase the version number of the API. 
    See our [reference guide](/api-documentation/docs/reference-guide#versioning) for more on versioning.

    # Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    - 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    - 400 to 499 if it failed because of a client error by your application
    - 500 to 599 if it failed because of an error on our server
    
    Errors specific to each API are shown in the Endpoints section, under Response. See our 
    [reference guide](/api-documentation/docs/reference-guide#errors) for more on errors.
  
servers:
- url: https://test-api.service.hmrc.gov.uk/hello
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/hello
  description: Production

components:
  responses:
    badOrExpiredTokenResponse:
      description: |
        Bad or expired token.
        This can happen if the user or HMRC revoked or expired an access token.
        To fix, you should re-authenticate the user.
      content:
        application/json:
          example:
    forbiddenResponse:
      description: |
        Bad OAuth request (wrong consumer key, bad nonce, expired
        timestamp...). Unfortunately, re-authenticating the user won't help here.
      content:
        application/json:
          example:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json",
          "application/vnd.hmrc.1.0+xml"
        ]
      required: true

    forename:
      name: forename
      description: The forename of the user
      in: path
      schema:
        type: string
      required: true

    middlename:
      name: middlename
      description: The middlename of the user
      in: path
      schema:
        type: string
      required: true

    surname:
      name: surname
      description: The surname of the user
      in: path
      schema:
        type: string
      required: true

  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            hello: access hello user
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
paths:
  /world:
    get:
      summary: Say hello world
      description: |
        A simple example for integrating with an unrestricted service.

        Any request to this endpoint initiates a 'Hello World' response.
      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello World"
                }
      security:
      - {}
                
  /user:
    get:
      summary: Say hello user
      description: |
        A simple example for integrating with a user-restricted service, using an OAuth 2.0 `access_token`.

        Any authorised request to this endpoint initiates a 'Hello User' response.
      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello User"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example: 
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
      - userRestricted:
        - hello
        
  /application:
    get:
      summary: Say hello application
      description: | 
        A simple example for integrating with an application-restricted service, using an OAuth 2.0 `access_token`.

        Any authorised request to this endpoint initiates a 'Hello Application' response.

      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello Application"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example: 
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
      - applicationRestricted: []

  /world/{forename}:
    get:
      summary: Forename
      description: |
        A simple example for integrating with an unrestricted service.

        Any request to this endpoint initiates a 'Hello World' response.
      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/forename'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello World"
                }
      security:
        - {}

  /world/{forename}/{surname}:
    get:
      summary: Forename and Surname
      description: |
        A simple example for integrating with an unrestricted service.

        Any request to this endpoint initiates a 'Hello World' response.
      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/forename'
        - $ref: '#/components/parameters/surname'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello World"
                }
      security:
        - {}

  /world/{forename}/{middlename}:
    get:
      summary: Forename and middlename
      description: |
        A simple example for integrating with an unrestricted service.

        Any request to this endpoint initiates a 'Hello World' response.
      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/forename'
        - $ref: '#/components/parameters/middlename'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello World"
                }
      security:
        - {}