
openapi: "3.0.3"

info:
  version: 1.0.0
  title: Hello World
  description: An example API used as a tutorial for software developers to test their application can connect with the HMRC API Platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
    
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/
  description: Production

components:
  responses:
    badOrExpiredTokenResponse:
      description: |
        Bad or expired token.
        This can happen if the user or HMRC revoked or expired an access token.
        To fix, you should re-authenticate the user.
      content:
        application/json:
          example:
    forbiddenResponse:
      description: |
        Bad OAuth request (wrong consumer key, bad nonce, expired
        timestamp...). Unfortunately, re-authenticating the user won't help here.
      content:
        application/json:
          example:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json",
          "application/vnd.hmrc.1.0+xml"
        ]
      required: true
  securitySchemes:
    oauth2:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows: 
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:hello: access hello user
    serverTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: HMRC Server token
      description: HMRC supports http bearer token authenticating applciation-restricted API requests

paths:
  /hello/world:
    get:
      summary: A simple example for integrating with an unrestricted service.
      operationId: world
      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello World"
                }
                
  /hello/user:
    get:
      summary: A simple example for integrating with a user restricted service.
      operationId: user
      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello User"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example: 
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
      - oauth2:
        - read:hello
        
  /hello/application:
    get:
      summary: A simple example for integrating with an application restricted service.
      operationId: application
      tags:
      - api-example-microservice
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message" : "Hello Application"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example: 
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
      - serverTokenAuth: []
